import { StyleSheet } from "react-native";

const BASE_SIZE = 20;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#141515",
  },
  taskdetail: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#0B2C25",
    marginTop: 3,
  },
  taskcontainer: {
    marginTop: 18,
    width: "90%",
    height: "23%",
    backgroundColor: "#040505",
    flexDirection: "row",
    borderRadius: 9,
    alignSelf: "center",
  },
  header: {
    marginTop: 10,
    marginLeft: 15,
    fontWeight: "bold",
  },
  headercontainer: {
    flex: 1,
    padding: 10,
    margin: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  txt: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FAFAFA",
    margin: 15,
  },
  txt1: {
    fontSize: 15,
    color: "#f0f0f0",
    position: "absolute",
    right: 8,
    top: 2,
    fontWeight: "600",
  },
  textContainer: {
    width: "50%",
    height: "30%",
    marginTop: -3,
  },
  taskstatus: {
    marginTop: 10,
    width: "50%",
    height: "50%",
  },
  tickicon: {
    position: "absolute",
    top: 1,
    right: 90,
  },
  circlecontainer: {
    width: "70%",
    height: "36%",
    position: "absolute",
    backgroundColor: "#2DAF95",
    flexDirection: "row",
    alignSelf: "flex-end",
    borderTopLeftRadius: 45,
    borderBottomLeftRadius: 45,
    top: "3.5%",
  },
  datecontainer: {
    color: "#556969",
    fontWeight: "bold",
    fontSize: 13,
    paddingLeft: 6.5,
  },
  calendaricon: {
    position: "absolute",
    top: "25%",
    left: "5.8%",
    flexDirection: "row",
    width: "50.3%",
    height: "15%",
    justifyContent: "space-between",
  },
  driverInfo: {
    position: "absolute",
    top: "66.5%",
    width: "100%",
    height: "38%",
    backgroundColor: "#05120F",
    borderBottomLeftRadius: 9,
    borderBottomRightRadius: 9,
  },
  img: {
    width: "70%",
    height: "70%",
    borderRadius: 35,
    position: "absolute",
    left: "-26%",
    top: "17%",
  },
  staricon: {
    position: "absolute",
    right: "15%",
    top: "27%",
  },
  mailicon: {
    position: "absolute",
    left: "20%",
    top: "1%",
  },
  rating: {
    color: "#556969",
    position: "absolute",
    right: "6%",
    top: "26%",
    fontWeight: "bold",
    fontSize: 16.3,
  },
  drivername: {
    color: "#2DAF95",
    position: "absolute",
    top: "12%",
    left: "17.3%",
    fontWeight: "bold",
    fontSize: 12,
  },
  phoneicon: {
    position: "absolute",
    left: "20%",
    top: "8%",
  },
  location: {
    position: "absolute",
    top: "97%",
    left: "1%",
  },
  pickuplocation: {
    color: "#C7D6D6",
    fontSize: 12,
    position: "absolute",
    left: "15%",
    top: "93%",
    fontWeight: "700",
  },
  dropofflocation: {
    color: "#C7D6D6",
    fontSize: 12,
    position: "absolute",
    left: "126%",
    top: "93%",
    fontWeight: "700",
  },
  dashedlines: {
    color: "#556969",
    position: "absolute",
    left: "77%",
    top: "81%",
    fontWeight: "bold",
  },
  btn: {
    position: "absolute",
    top: "46.9%",
    left: "26.8%",
    height: "27%",
    width: "8%",
    borderRadius: 80,
    backgroundColor: "#0B2C25",
  },
  btn1: {
    backgroundColor: "#0B2C25",
    position: "absolute",
    height: "28%",
    width: "7%",
    top: "46.9%",
    left: "17.4%",
    borderRadius: 80,
  },
  circlesContainer: {
    position: "absolute",
    width: BASE_SIZE,
    height: BASE_SIZE,
    borderRadius: BASE_SIZE,
    backgroundColor: "#362408",
    top: "79%",
    left: "500%",
  },
  circle_1: {
    top: "18.2%",
    left: "20.7%",
    position: "absolute",
    width: BASE_SIZE * 0.6,
    height: BASE_SIZE * 0.6,
    borderRadius: BASE_SIZE / 2,
    backgroundColor: "#5c3b0a",
  },
  circle_2: {
    top: "29%",
    left: "33%",
    position: "absolute",
    width: BASE_SIZE * 0.35,
    height: BASE_SIZE * 0.35,
    borderRadius: BASE_SIZE / 2,
    backgroundColor: "#EB7F01",
  },
  cont: {
    position: "absolute",
    top: "85%",
    right: "-7%",
  },
  dropoffaddress: {
    color: "#556969",
    position: "absolute",
    top: "175%",
    left: "126%",
    fontWeight: "600",
    fontSize: 12,
  },
  pickupad: {
    color: "#556969",
    position: "absolute",
    top: "175%",
    left: "13%",
    fontWeight: "600",
    fontSize: 12,
  },
});

export default styles;
